"""End-to-end test of the polyglot coding path against a mock OpenAI server.

Runs aider's official benchmark.py (cloned by `quant-bench setup`) with a fake
model that returns a trivial whole-file edit. Verifies the full pipeline:
benchmark.py -> aider -> 200 response -> edit applied -> pytest ->
.aider.results.json -> run_coding summary. Skipped unless setup was run.
"""

import json
import re
import threading
import time
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path

import pytest

from quant_bench.coding import run_coding

REPO_ROOT = Path(__file__).resolve().parent.parent
BENCHMARK_ROOT = REPO_ROOT / "tmp.benchmarks"

MOCK_MARKER = "# generated by quant-bench mock"


class _MockHandler(BaseHTTPRequestHandler):
    model = "mockmodel"

    def _send(self, obj: dict) -> None:
        body = json.dumps(obj).encode()
        self.send_response(200)
        self.send_header("Content-Type", "application/json")
        self.send_header("Content-Length", str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def do_GET(self):
        if self.path.startswith("/v1/models"):
            self._send({"data": [{"id": self.model, "object": "model", "owned_by": "quant-bench"}]})
        elif self.path.startswith("/health"):
            self._send({"status": "ok"})
        else:
            self.send_error(404)

    def do_POST(self):
        n = int(self.headers.get("Content-Length", 0))
        req = json.loads(self.rfile.read(n) or b"{}")
        messages = req.get("messages", [])
        fname = "exercise.py"
        for m in messages:
            for match in re.findall(r"([^\s`]+\.py)[ \t]*\r?\n[ \t]*```", str(m.get("content", ""))):
                fname = match.split("/")[-1]
        content = (
            f"{fname}\n```\n{MOCK_MARKER}\n\n\n"
            "def solve():\n    return 42\n```\n"
        )
        self._send(
            {
                "id": "mock-1",
                "object": "chat.completion",
                "created": int(time.time()),
                "model": self.model,
                "choices": [
                    {
                        "index": 0,
                        "message": {"role": "assistant", "content": content},
                        "finish_reason": "stop",
                    }
                ],
                "usage": {
                    "prompt_tokens": max(1, sum(len(str(m.get("content", ""))) for m in messages) // 4),
                    "completion_tokens": max(1, len(content) // 4),
                    "total_tokens": 2,
                },
            }
        )

    def log_message(self, *args):
        pass


@pytest.fixture()
def mock_server():
    srv = HTTPServer(("127.0.0.1", 0), _MockHandler)
    t = threading.Thread(target=srv.serve_forever, daemon=True)
    t.start()
    yield f"http://127.0.0.1:{srv.server_address[1]}"
    srv.shutdown()


@pytest.mark.skipif(
    not (BENCHMARK_ROOT / "aider" / "benchmark" / "benchmark.py").is_file(),
    reason="run `quant-bench setup` first (clones aider + polyglot-benchmark)",
)
def test_run_coding_success_path(mock_server, tmp_path):
    res = run_coding(
        benchmark_root=BENCHMARK_ROOT,
        server_url=mock_server,
        model_slug="mockmodel",
        server_ctx=4096,
        edit_format="whole",
        languages="python",
        tries=1,
        num_tests=1,
        log_path=tmp_path / "coding_mock.log",
    )
    assert res.completed_tests >= 1
    expected_total = len(
        list((BENCHMARK_ROOT / "polyglot-benchmark" / "python" / "exercises" / "practice").glob("*"))
    )
    assert res.total_tests == expected_total
    assert res.prompt_tokens > 0
    assert res.completion_tokens > 0
    for r in res.raw:
        assert (r.get("num_error_outputs") or 0) == 0, f"LLM error in result: {r}"
    edited = [
        f
        for f in res.run_dir.glob("python/exercises/practice/*/*.py")
        if "test" not in f.name
    ]
    assert edited, f"no exercise file found under {res.run_dir}"
    assert any(MOCK_MARKER in f.read_text() for f in edited), "mock edit was not applied"
